### ISSUE TITLE
Utiliser de nouvelles règles de lint

### ISSUE THREAD

**Issue by maelchiotti** [studiorvandco/cpm_app#114]
Utiliser [lint](https://pub.dev/packages/lint). À faire à la fin.

```[tasklist]
### Tasks
- [ ] Ajouter le package
- [ ] Appliquer toutes les corrections suggérées
- [ ] Vérifier que les `@ignore` utilisés sont toujours nécessaires
```
