### ISSUE TITLE
Améliorer les traductions

### ISSUE THREAD

**Issue by maelchiotti** [studiorvandco/cpm_app#119]
```[tasklist]
### Tasks
- [x] Utiliser l10n
- [x] Reprendre les traductions de zéro pour s'assurer qu'elles sont toutes correctes
- [x] Remplacer toutes les traductions
- [x] Améliorer le [wiki](https://github.com/StudioRvAndCo/CPM-frontend/wiki/Localize)
```
